server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # Cấu hình CORS
      globalcors:
        add-to-simple-url-handler-mapping: true # Thêm dòng này
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true # BẮT BUỘC phải có dòng này để xử lý JWT/Login

      routes:
        # 1. Room Service
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/rooms/**, /api/dich-vu/**, /api/loai-phong/**

        # 2. Booking Service
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**, /api/services/**

        # 3. Identity Service
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
<<<<<<< HEAD
            - Path=/api/auth/**
=======
            - Path=/api/auth/**, /api/users/**, /api/permissions/**, /api/roles/**, /api/admin/**
>>>>>>> parent of 0544b01 (UpDocker)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/