server.port=8082
spring.application.name=BOOKING-SERVICE
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=Admin1234
# QUAN TRỌNG: Chuyển ddl-auto thành none để Hibernate không cố gắng sửa/kiểm tra DB nữa
spring.jpa.hibernate.ddl-auto=none
# Tắt Open-in-view để quản lý transaction chặt chẽ hơn, tránh giữ connection quá lâu
spring.jpa.open-in-view=false
# Map đúng tên bảng viết hoa
spring.jpa.properties.hibernate.boot.model.naming.physical_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/