server.port=8081
spring.application.name=ROOM-SERVICE
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=Admin1234
spring.jpa.hibernate.ddl-auto=update
# Giới hạn cho 1 file
spring.servlet.multipart.max-file-size=10MB
# Giới hạn cho tổng dữ liệu trong 1 request (bao gồm nhiều file và text)
spring.servlet.multipart.max-request-size=10MB
# Map đúng tên bảng viết hoa
spring.jpa.properties.hibernate.boot.model.naming.physical_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/