# Port mặc định của Eureka Server
server.port=8761

# Tên ứng dụng
spring.application.name=discovery-server

# False: Vì đây là Server, nó không cần tự đăng ký với chính nó
eureka.client.register-with-eureka=false

# False: Nó không cần tải danh sách registry từ server khác
eureka.client.fetch-registry=false